const FEED_URL="https://api.github.com/repos/matzoka/matzoka.github.io/issues/1",Y1="https://query1.finance.yahoo.com/v8/finance/chart/JPY%3DX?interval=1m&range=1d",Y15="https://query1.finance.yahoo.com/v8/finance/chart/JPY%3DX?interval=15m&range=5d",STORE="fx-usdjpy-short-settings-v1",REFRESH=5*60*1000,$=id=>document.getElementById(id),yen=new Intl.NumberFormat("ja-JP",{maximumFractionDigits:0,signDisplay:"always"}),num=new Intl.NumberFormat("ja-JP",{maximumFractionDigits:3});let settings={entry:null,position:null},quote=null,candles=[],chartModel=null;
function bootstrap(){const p=new URLSearchParams(location.hash.slice(1)),entry=Number(p.get("entry")),position=Number(p.get("position"));if(entry>0&&position>0){localStorage.setItem(STORE,JSON.stringify({entry,position}));history.replaceState(null,"",location.pathname+location.search)}}
function load(){try{const s=JSON.parse(localStorage.getItem(STORE)||"null");if(s?.entry>0&&s?.position>0)settings=s}catch(_){}$("entryInput").value=settings.entry??"";$("positionInput").value=settings.position??"";render()}
function save(){const entry=Number($("entryInput").value),position=Number($("positionInput").value);if(!(entry>0&&position>0))return stat("平均売値と建玉を正しく入力してください。",1);settings={entry,position};localStorage.setItem(STORE,JSON.stringify(settings));stat("このブラウザに保存しました。");render();draw()}
function stat(s,e=0){$("status").textContent=s;$("status").className=e?"status error":"status"}function cstat(s,e=0){$("chartStatus").textContent=s;$("chartStatus").className=e?"status error":"status"}
function render(){$("entryView").textContent=settings.entry?settings.entry.toFixed(3)+"円":"未設定";$("positionView").textContent=settings.position?num.format(settings.position)+" USD":"未設定";if(!quote)return;const r=Number(quote.rate);$("rate").textContent=r.toFixed(3)+"円";$("quoteTime").textContent=quote.quote_time_jst||"---";if(!(settings.entry>0&&settings.position>0)){$("pnl").textContent="設定してください";return}const d=settings.entry-r,p=d*settings.position;$("difference").textContent=(d>=0?"+":"")+d.toFixed(3)+"円";$("pnl").textContent=yen.format(Math.round(p))+"円";$("pnl").className="pnl "+(p>.5?"good":p<-.5?"bad":"");$("direction").textContent=p>.5?"円高方向へ進み、現在は概算含み益です。":p<-.5?"円安方向へ進み、現在は概算含み損です。":"ほぼ建値です。";$("target152").textContent=yen.format(Math.round((settings.entry-152)*settings.position))+"円";$("target147").textContent=yen.format(Math.round((settings.entry-147)*settings.position))+"円"}
async function j(url){let r;try{r=await fetch(url+(url.includes("?")?"&":"?")+"t="+Date.now(),{cache:"no-store"})}catch(_){r=null}if(!r||!r.ok){const p="https://corsproxy.io/?url="+encodeURIComponent(url);r=await fetch(p+"&t="+Date.now(),{cache:"no-store"})}if(!r.ok)throw Error("HTTP "+r.status);return r.json()}
async function scheduled(){const r=await fetch(FEED_URL+"?t="+Date.now(),{headers:{Accept:"application/vnd.github+json"},cache:"no-store"});if(!r.ok)throw Error("HTTP "+r.status);const f=JSON.parse((await r.json()).body);if(!(Number(f.rate)>0))throw Error("レートが不正です");return f}
async function live(){const x=(await j(Y1))?.chart?.result?.[0],m=x?.meta;if(!m?.regularMarketPrice)throw Error("最新値を取得できません");const t=m.regularMarketTime||Date.now()/1000;return{rate:Number(m.regularMarketPrice),quote_time_jst:new Date(t*1000).toLocaleString("ja-JP",{timeZone:"Asia/Tokyo"})+" JST"}}
async function bars(){const x=(await j(Y15))?.chart?.result?.[0],ts=x?.timestamp||[],q=x?.indicators?.quote?.[0]||{},a=[];for(let i=0;i<ts.length;i++){const o=+q.open?.[i],h=+q.high?.[i],l=+q.low?.[i],c=+q.close?.[i];if([o,h,l,c].every(Number.isFinite))a.push({t:+ts[i],o,h,l,c})}if(a.length<80)throw Error("15分足データが不足しています");return a.slice(-180)}
function sma(a,n){const out=Array(a.length).fill(null);let s=0;for(let i=0;i<a.length;i++){s+=a[i];if(i>=n)s-=a[i-n];if(i>=n-1)out[i]=s/n}return out}function boll(a,n=20,k=2){const mid=sma(a,n),up=Array(a.length).fill(null),lo=Array(a.length).fill(null);for(let i=n-1;i<a.length;i++){let v=0;for(let z=i-n+1;z<=i;z++)v+=(a[z]-mid[i])**2;const d=Math.sqrt(v/n);up[i]=mid[i]+k*d;lo[i]=mid[i]-k*d}return{mid,up,lo}}
function draw(){if(!candles.length)return;const cv=$("chart"),ctx=cv.getContext("2d"),dpr=devicePixelRatio||1,w=cv.clientWidth||850,h=cv.clientHeight||420;cv.width=w*dpr;cv.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle="#0d1524";ctx.fillRect(0,0,w,h);const all=candles,cl=all.map(x=>x.c),M5=sma(cl,5),M25=sma(cl,25),M75=sma(cl,75),B=boll(cl),start=Math.max(0,all.length-96),v=all.slice(start),series={m5:M5.slice(start),m25:M25.slice(start),m75:M75.slice(start),bm:B.mid.slice(start),bu:B.up.slice(start),bl:B.lo.slice(start)},vals=v.flatMap(x=>[x.h,x.l]);for(const key of ["m5","m25","m75","bu","bl"])for(const x of series[key])if(x!=null)vals.push(x);if($("entryLine").checked&&settings.entry>0)vals.push(settings.entry);let min=Math.min(...vals),max=Math.max(...vals),pad=Math.max((max-min)*.07,.025);min-=pad;max+=pad;const m={l:10,r:62,t:22,b:28},pw=w-m.l-m.r,ph=h-m.t-m.b,sy=p=>m.t+(max-p)/(max-min)*ph,sx=i=>m.l+(i+.5)*pw/v.length,step=pw/v.length,bw=Math.max(2,Math.min(8,step*.58));ctx.strokeStyle="rgba(156,175,199,.16)";ctx.fillStyle="#9cafc7";ctx.font="11px system-ui";ctx.textAlign="right";ctx.textBaseline="middle";for(let i=0;i<=5;i++){const y=m.t+ph*i/5,p=max-(max-min)*i/5;ctx.beginPath();ctx.moveTo(m.l,y);ctx.lineTo(w-m.r+4,y);ctx.stroke();ctx.fillText(p.toFixed(3),w-4,y)}
function line(a,color,width=1.4,dash=[]){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.beginPath();let on=0;for(let i=0;i<a.length;i++){if(a[i]==null){on=0;continue}const x=sx(i),y=sy(a[i]);if(!on){ctx.moveTo(x,y);on=1}else ctx.lineTo(x,y)}ctx.stroke();ctx.restore()}
if($("bb").checked){ctx.save();ctx.fillStyle="rgba(167,139,250,.08)";ctx.beginPath();let begun=0;for(let i=0;i<v.length;i++)if(series.bu[i]!=null){const x=sx(i),y=sy(series.bu[i]);if(!begun){ctx.moveTo(x,y);begun=1}else ctx.lineTo(x,y)}for(let i=v.length-1;i>=0;i--)if(series.bl[i]!=null)ctx.lineTo(sx(i),sy(series.bl[i]));ctx.closePath();ctx.fill();ctx.restore();line(series.bu,"rgba(167,139,250,.75)",1);line(series.bl,"rgba(167,139,250,.75)",1);line(series.bm,"rgba(167,139,250,.45)",1,[4,3])}
v.forEach((c,i)=>{const x=sx(i),up=c.c>=c.o,col=up?"#42d392":"#ff6b7a";ctx.strokeStyle=col;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x,sy(c.h));ctx.lineTo(x,sy(c.l));ctx.stroke();ctx.fillStyle=col;ctx.fillRect(x-bw/2,Math.min(sy(c.o),sy(c.c)),bw,Math.max(1.5,Math.abs(sy(c.o)-sy(c.c))))});if($("ma5").checked)line(series.m5,"#e3d400",1.5);if($("ma25").checked)line(series.m25,"#ff7fb8",1.5);if($("ma75").checked)line(series.m75,"#3b82f6",1.5);if($("entryLine").checked&&settings.entry>0){line(Array(v.length).fill(settings.entry),"rgba(255,255,255,.78)",1,[7,5]);ctx.fillStyle="#fff";ctx.textAlign="left";ctx.fillText("平均売値 "+settings.entry.toFixed(3),m.l+4,sy(settings.entry)-9)}ctx.fillStyle="#9cafc7";ctx.textAlign="center";ctx.textBaseline="top";for(const i of [0,24,48,72,95])if(v[i])ctx.fillText(new Date(v[i].t*1000).toLocaleTimeString("ja-JP",{timeZone:"Asia/Tokyo",hour:"2-digit",minute:"2-digit"}),sx(i),h-m.b+7);chartModel={v,sx,sy,w,h,m};$("pngButton").disabled=false}
async function periodic(){stat("定期フィードを確認しています…");try{quote=await scheduled();render();stat("定期フィード取得完了："+new Date().toLocaleString("ja-JP"))}catch(e){stat("定期フィードを取得できませんでした："+e.message,1)}}
async function now(){const b=$("refreshButton");b.disabled=true;stat("最新値を照会しています…");cstat("15分足とテクニカルを計算しています…");try{const [q,c]=await Promise.all([live(),bars()]);quote=q;candles=c;render();draw();stat("最新値を直接取得しました："+new Date().toLocaleString("ja-JP"));cstat("15分足96本、MA 5・25・75、ボリンジャーバンド20・±2σを表示しました。") }catch(e){stat("直接取得に失敗したため定期フィードへ切り替えます："+e.message,1);cstat("チャート取得に失敗しました："+e.message,1);await periodic()}finally{b.disabled=false}}
function png(){if(!candles.length)return;const a=document.createElement("a");a.download="USDJPY_15m_"+new Date().toISOString().slice(0,16).replace(/[:T]/g,"-")+".png";a.href=$("chart").toDataURL("image/png");a.click()}
function tooltip(e){if(!chartModel)return;const r=$("chart").getBoundingClientRect(),x=e.clientX-r.left,{v,sx}=chartModel;let i=Math.round((x-sx(0))/(sx(1)-sx(0)));i=Math.max(0,Math.min(v.length-1,i));const c=v[i],t=$("tip");t.innerHTML=new Date(c.t*1000).toLocaleString("ja-JP",{timeZone:"Asia/Tokyo"})+"<br>O "+c.o.toFixed(3)+"　H "+c.h.toFixed(3)+"<br>L "+c.l.toFixed(3)+"　C "+c.c.toFixed(3);t.style.display="block";t.style.left=Math.min(innerWidth-190,e.clientX+12)+"px";t.style.top=Math.max(8,e.clientY-72)+"px"}
$("saveButton").onclick=save;$("refreshButton").onclick=now;$("pngButton").onclick=png;for(const id of ["ma5","ma25","ma75","bb","entryLine"])$(id).onchange=draw;$("chart").addEventListener("mousemove",tooltip);$("chart").addEventListener("mouseleave",()=>$("tip").style.display="none");addEventListener("resize",draw);bootstrap();load();periodic();setInterval(periodic,REFRESH);